
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_LOADING="LOGIN_USER_LOGIN"
export const LOGIN_USER_FAILED="LOGIN_USER_FAILED"

export const SIGNUP_USER_SUCCESS="SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_LOADING="SIGNUP_USER_LOGIN"
export const SIGNUP_USER_FAILED="SIGNUP_USER_FAILED"

export const GET_MESSAGE_SUCCESS="GET_MESSAGE_SUCCESS"
export const GET_MESSAGE_LOADING="GET_MESSAGE_LOADING"
export const GET_MESSAGE_FAILED="GET_MESSAGE_FAILED"

export const SEND_MESSAGE_SUCCESS="SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_LOADING="SEND_MESSAGE_LOADING"
export const SEND_MESSAGE_FAILED="SEND_MESSAGE_FAILED"

export const LOGOUT_USER_SUCCESS="LOGOUT_USER_SUCCESS"
// export const LOGOUT_USER_LOADING="LOGOUT_USER_LOADING"
// export const LOGOUT_USER_FAILED="LOGOUT_USER_FAILED"